/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Action,
    ActionFromJSON,
    ActionFromJSONTyped,
    ActionToJSON,
    Feature,
    FeatureFromJSON,
    FeatureFromJSONTyped,
    FeatureToJSON,
    Resource,
    ResourceFromJSON,
    ResourceFromJSONTyped,
    ResourceToJSON,
    Skill,
    SkillFromJSON,
    SkillFromJSONTyped,
    SkillToJSON,
    Stat,
    StatFromJSON,
    StatFromJSONTyped,
    StatToJSON,
} from './';

/**
 * 
 * @export
 * @interface Encounter
 */
export interface Encounter {
    /**
     * 
     * @type {string}
     * @memberof Encounter
     */
    name: string;
    /**
     * 
     * @type {Array<Stat>}
     * @memberof Encounter
     */
    stats: Array<Stat>;
    /**
     * 
     * @type {Array<Resource>}
     * @memberof Encounter
     */
    resource: Array<Resource>;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof Encounter
     */
    resistances: { [key: string]: string; };
    /**
     * 
     * @type {Array<Skill>}
     * @memberof Encounter
     */
    skills: Array<Skill>;
    /**
     * 
     * @type {Array<Feature>}
     * @memberof Encounter
     */
    features: Array<Feature>;
    /**
     * 
     * @type {Array<Action>}
     * @memberof Encounter
     */
    actions: Array<Action>;
}

/**
* @export
* @enum {string}
*/
export enum EncounterResistancesEnum {
    Resistent = 'RESISTENT',
    Vulnerable = 'VULNERABLE',
    Immune = 'IMMUNE'
}

export function EncounterFromJSON(json: any): Encounter {
    return EncounterFromJSONTyped(json, false);
}

export function EncounterFromJSONTyped(json: any, ignoreDiscriminator: boolean): Encounter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'stats': ((json['stats'] as Array<any>).map(StatFromJSON)),
        'resource': ((json['resource'] as Array<any>).map(ResourceFromJSON)),
        'resistances': json['resistances'],
        'skills': ((json['skills'] as Array<any>).map(SkillFromJSON)),
        'features': ((json['features'] as Array<any>).map(FeatureFromJSON)),
        'actions': ((json['actions'] as Array<any>).map(ActionFromJSON)),
    };
}

export function EncounterToJSON(value?: Encounter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'stats': ((value.stats as Array<any>).map(StatToJSON)),
        'resource': ((value.resource as Array<any>).map(ResourceToJSON)),
        'resistances': value.resistances,
        'skills': ((value.skills as Array<any>).map(SkillToJSON)),
        'features': ((value.features as Array<any>).map(FeatureToJSON)),
        'actions': ((value.actions as Array<any>).map(ActionToJSON)),
    };
}


