/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Roll
 */
export interface Roll {
    /**
     * 
     * @type {number}
     * @memberof Roll
     */
    flatModifier: number;
    /**
     * 
     * @type {number}
     * @memberof Roll
     */
    diceSize: number;
    /**
     * 
     * @type {number}
     * @memberof Roll
     */
    diceAmount: number;
}

export function RollFromJSON(json: any): Roll {
    return RollFromJSONTyped(json, false);
}

export function RollFromJSONTyped(json: any, ignoreDiscriminator: boolean): Roll {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'flatModifier': json['flatModifier'],
        'diceSize': json['diceSize'],
        'diceAmount': json['diceAmount'],
    };
}

export function RollToJSON(value?: Roll | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'flatModifier': value.flatModifier,
        'diceSize': value.diceSize,
        'diceAmount': value.diceAmount,
    };
}


