/* tslint:disable */
/* eslint-disable */
/**
 * Homebrewer\'s Tools: Core
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ValueModifier,
    ValueModifierFromJSON,
    ValueModifierFromJSONTyped,
    ValueModifierToJSON,
} from './';

/**
 * 
 * @export
 * @interface Resource
 */
export interface Resources {
    /**
     * 
     * @type {string}
     * @memberof Resources
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof Resources
     */
    maxValue: number;
    /**
     * 
     * @type {number}
     * @memberof Resources
     */
    currentValue: number;
    /**
     * 
     * @type {number}
     * @memberof Resources
     */
    baseValue: number;
    /**
     * 
     * @type {Array<ValueModifier>}
     * @memberof Resources
     */
    modifiers: Array<ValueModifier>;
}

export function ResourceFromJSON(json: any): Resources {
    return ResourceFromJSONTyped(json, false);
}

export function ResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Resources {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'maxValue': json['maxValue'],
        'currentValue': json['currentValue'],
        'baseValue': json['baseValue'],
        'modifiers': ((json['modifiers'] as Array<any>).map(ValueModifierFromJSON)),
    };
}

export function ResourceToJSON(value?: Resources | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'maxValue': value.maxValue,
        'currentValue': value.currentValue,
        'baseValue': value.baseValue,
        'modifiers': ((value.modifiers as Array<any>).map(ValueModifierToJSON)),
    };
}


