/* tslint:disable */
/* eslint-disable */
/**
 * Homebrewer\'s Tools: Core
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Action,
    ActionFromJSON,
    ActionFromJSONTyped,
    ActionToJSON,
    Feature,
    FeatureFromJSON,
    FeatureFromJSONTyped,
    FeatureToJSON,
    Skill,
    SkillFromJSON,
    SkillFromJSONTyped,
    SkillToJSON,
} from './';

/**
 * 
 * @export
 * @interface Encounter
 */
export interface Encounter {
    /**
     * 
     * @type {string}
     * @memberof Encounter
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof Encounter
     */
    challengeRating: number;
    /**
     * 
     * @type {number}
     * @memberof Encounter
     */
    armorClass: number;
    /**
     * 
     * @type {number}
     * @memberof Encounter
     */
    hitPoints: number;
    /**
     * 
     * @type {number}
     * @memberof Encounter
     */
    strength: number;
    /**
     * 
     * @type {number}
     * @memberof Encounter
     */
    dexterity: number;
    /**
     * 
     * @type {number}
     * @memberof Encounter
     */
    constitution: number;
    /**
     * 
     * @type {number}
     * @memberof Encounter
     */
    intelligence: number;
    /**
     * 
     * @type {number}
     * @memberof Encounter
     */
    wisdom: number;
    /**
     * 
     * @type {number}
     * @memberof Encounter
     */
    charisma: number;
    /**
     * 
     * @type {number}
     * @memberof Encounter
     */
    moveSpeed: number;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof Encounter
     */
    resistances: { [key: string]: string; };
    /**
     * 
     * @type {Array<Skill>}
     * @memberof Encounter
     */
    skills: Array<Skill>;
    /**
     * 
     * @type {Array<Feature>}
     * @memberof Encounter
     */
    features: Array<Feature>;
    /**
     * 
     * @type {Array<Action>}
     * @memberof Encounter
     */
    actions: Array<Action>;
}

/**
* @export
* @enum {string}
*/
export enum EncounterResistancesEnum {
    Resistent = 'RESISTENT',
    Vulnerable = 'VULNERABLE',
    Immune = 'IMMUNE'
}

export function EncounterFromJSON(json: any): Encounter {
    return EncounterFromJSONTyped(json, false);
}

export function EncounterFromJSONTyped(json: any, ignoreDiscriminator: boolean): Encounter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'challengeRating': json['challengeRating'],
        'armorClass': json['armorClass'],
        'hitPoints': json['hitPoints'],
        'strength': json['strength'],
        'dexterity': json['dexterity'],
        'constitution': json['constitution'],
        'intelligence': json['intelligence'],
        'wisdom': json['wisdom'],
        'charisma': json['charisma'],
        'moveSpeed': json['moveSpeed'],
        'resistances': json['resistances'],
        'skills': ((json['skills'] as Array<any>).map(SkillFromJSON)),
        'features': ((json['features'] as Array<any>).map(FeatureFromJSON)),
        'actions': ((json['actions'] as Array<any>).map(ActionFromJSON)),
    };
}

export function EncounterToJSON(value?: Encounter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'challengeRating': value.challengeRating,
        'armorClass': value.armorClass,
        'hitPoints': value.hitPoints,
        'strength': value.strength,
        'dexterity': value.dexterity,
        'constitution': value.constitution,
        'intelligence': value.intelligence,
        'wisdom': value.wisdom,
        'charisma': value.charisma,
        'moveSpeed': value.moveSpeed,
        'resistances': value.resistances,
        'skills': ((value.skills as Array<any>).map(SkillToJSON)),
        'features': ((value.features as Array<any>).map(FeatureToJSON)),
        'actions': ((value.actions as Array<any>).map(ActionToJSON)),
    };
}


